pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - check-success=build
      - base=main
      - label=auto-merge
    actions:
      merge:
        method: merge
        strict: smart+fasttrack
        strict_method: rebase