on: [push]

env:
    BRANCH: ${GITHUB_REF##*/}
    VOLATILE_BRANCH: ${{ ! (github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/heads/release-')) }}

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: validate branch name
        run: |
          python3 -c "import sys; print('$BRANCH'); sys.exit(1 if 'fail' in '$BRANCH' else 0)"
